[help]
prefix = "The following commands are available (prefixed by `!`):"
suffix = "-# For more information on individual commands use `helpall` for a full list in a DM"
general = """general:
- `rules` - a refresher on where you can find various rules
- `roles` - pointers to where roles can be self-assigned
- `guild` - a link to the {CHANNELS_GENERAL["guild"]} channel and some reminders of requirements to join the guild
- `mods` - reminders on how you can contact us
- `addons` - recommended addons for WoW
- `website` - a link to the No Pressure website
- `recruitmentdiscord` - a link to the WoW recruitment EU discord"""
dungeons = """dungeons:
- `ilvl` - the minimum ilvls allowed for each m+ difficulty (this adapts depending on which channel it's called in)
- `mxp` - a reminder of the rule about what experience is expected for keys
- `mparty` - a reminder of the rule about who you can decline from keys
- `lfg` - where you can find instructions on how to join dungeons and use the dungeon buddy"""
raids = """raids:
- `raidjoin` - where to find information about joining raids
- `raidsetup` - where to find information about setting up raids"""
short = """general: `rules`, `roles`, `guild`, `mods`, `addons`, `website`, `recruitmentdiscord`
dungeons: `ilvl`, `mxp`, `mparty`, `lfg`
raids: `raidjoin`, `raidsetup`"""
